
name: Test Install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create minimal Brewfile for testing
        run: |
          # No need to install all packages, just stow
          echo 'brew "stow"' > homedir/.Brewfile
      - name: Run install script
        run: ./install.zsh
      - name: Verify installation
        run: |
          if [ ! -L "$HOME/.zshrc" ]; then
            echo ".zshrc symlink not found!"
            exit 1
          fi
